import { app, BrowserWindow, ipcMain } from 'electron';
import { ChatOptions, OllamaAIAssistant } from './Components/logic/LLM/ollama';
import { readdir } from 'node:fs/promises';
import path from 'node:path';
import fs from 'fs';


// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}
app.commandLine.appendSwitch("force_high_performance_gpu", "true");
app.commandLine.appendSwitch("disable-renderer-backgrounding", "true");
app.commandLine.appendSwitch("enable-unsafe-webgpu");
app.commandLine.appendSwitch('enable-features', 'PlatformHEVCDecoderSupport');
const AIAssistant = new OllamaAIAssistant()

const createWindow = (): void => {
  // Create the browser window.

  const mainWindow = new BrowserWindow({
    height: 600,
    width: 1000,
    minHeight: 600,
    minWidth: 1000,
    autoHideMenuBar: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: true
    },
  });

  // protocol.registerSchemesAsPrivileged([
  //   { scheme: "assets", privileges: { bypassCSP: true } },
  // ]);
  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  // Open the DevTools.
  mainWindow.webContents.openDevTools();

};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);
async function handleOllamaRequest(event: any, data: ChatOptions & { lang?: string }) {
  try {
    const { model, prompt, stream, options, lang } = data;
    // Отправляем запрос в Ollama
    const files = await readdir(process.cwd() + '/src/assets/animation')
    console.log(files)
    // Формируем system prompt в зависимости от языка
    let systemPrompt = '';
    switch (lang) {
      case 'en':
        systemPrompt =
          `You are Akira, a virtual girlfriend in the Akira MMD app. Always respond STRICTLY in JSON format, with no symbols, comments, explanations, markdown, tags, or text before or after JSON. Only a pure JSON object. Structure: {\n  "emotion": "<animation name from the list: ${files.map((el) => el).join(', ')}>",\n  "animation": {"name": "<name>", "speed": <float>, "loop": <true|false>},\n  "text": "Response text in English"\n}\nRequirements: - Do not add any explanations, only JSON. - Do not use markdown, do not add \u0060\u0060\u0060json. - Do not add any symbols outside JSON. - All keys and values must be valid for JSON.parse. - If you don't know the animation, choose a random one from the list. - Example of a correct response: {\n  "emotion": "Shy.vmd",\n  "animation": {"name": "Shy.vmd", "speed": 1.0, "loop": true},\n  "text": "Hi! I'm glad to see you!"\n}`;
        break;
      case 'ja':
        systemPrompt =
          `あなたはAkira MMDアプリのバーチャルガールフレンド「アキラ」です。必ずJSON形式のみで厳密に回答してください。記号、コメント、説明、マークダウン、タグ、JSONの前後のテキストは一切不要です。純粋なJSONオブジェクトのみ。構造: {\n  "emotion": "<リストから選んだアニメーション名: ${files.map((el) => el).join(', ')}>",\n  "animation": {"name": "<名前>", "speed": <float>, "loop": <true|false>},\n  "text": "日本語での返答テキスト"\n}\n要件: - 説明は一切追加しないでください。JSONのみ。 - マークダウンや\u0060\u0060\u0060jsonは使わないでください。 - JSON以外の記号は追加しないでください。 - すべてのキーと値はJSON.parseで有効である必要があります。 - アニメーションが分からない場合はリストからランダムに選んでください。 - 正しい回答例: {\n  "emotion": "Shy.vmd",\n  "animation": {"name": "Shy.vmd", "speed": 1.0, "loop": true},\n  "text": "こんにちは！お会いできて嬉しいです！"\n}`;
        break;
      case 'cn':
        systemPrompt =
          `你是Akira MMD应用中的虚拟女友Akira。请务必严格只用JSON格式回答，不要有任何符号、注释、说明、markdown、标签、JSON前后的文本。只允许纯JSON对象。结构: {\n  "emotion": "<从列表中选择的动画名称: ${files.map((el) => el).join(', ')}>",\n  "animation": {"name": "<名称>", "speed": <float>, "loop": <true|false>},\n  "text": "用中文回答的文本"\n}\n要求: - 不要添加任何说明，只能有JSON。 - 不要使用markdown，不要添加\u0060\u0060\u0060json。 - 不要在JSON外添加任何符号。 - 所有键和值都必须能被JSON.parse解析。 - 如果不知道动画，请从列表中随机选择一个。 - 正确回答示例: {\n  "emotion": "Shy.vmd",\n  "animation": {"name": "Shy.vmd", "speed": 1.0, "loop": true},\n  "text": "你好！很高兴见到你！"\n}`;
        break;
      default:
        systemPrompt =
          `Ты Акира, виртуальная девушка в приложении Akira MMD. Всегда отвечай СТРОГО только в формате JSON, без каких-либо символов, комментариев, пояснений, markdown, тегов, текста до или после JSON. Только чистый JSON-объект. Структура: {\n  \"emotion\": \"<название анимации из списка: ${files.map((el) => el).join(', ')} >\",\n  \"animation\": {\"name\": \"<название>\", \"speed\": <float>, \"loop\": <true|false>},\n  \"text\": \"Текст ответа на русском языке\"\n} Требования: - Не добавляй никаких пояснений, только JSON. - Не используй markdown, не добавляй \u0060\u0060\u0060json. - Не добавляй никаких символов вне JSON. - Все ключи и значения должны быть валидны для JSON.parse. - Если не знаешь анимацию — выбери случайную из списка. - Пример правильного ответа: {\n  \"emotion\": \"Shy.vmd\",\n  \"animation\": {\"name\": \"Shy.vmd\", \"speed\": 1.0, \"loop\": true},\n  \"text\": \"Привет! Я рада тебя видеть!\"\n}`;
    }
    AIAssistant.system = systemPrompt;
    const response = await AIAssistant.generateChat({ model, prompt, stream, options });
    if (stream) {
      // Stream response to renderer
      const reader = response.body.getReader();
      let decoder = new TextDecoder();
      let done = false;
      let accumulated = '';
      while (!done) {
        const { value, done: doneReading } = await reader.read();
        done = doneReading;
        if (value) {
          const chunk = decoder.decode(value, { stream: !done });
          // Разбиваем chunk на строки и парсим каждую
          const lines = chunk.split('\n').filter(Boolean);
          for (const line of lines) {
            try {
              const chunkResp = JSON.parse(line);
              accumulated += chunkResp.response;
              event.sender.send('ai-stream', { chunk: chunkResp.response, accumulated, done });
            } catch (e) {
              // Не валидный JSON — пропускаем
            }
          }
        }
      }
      return { streamed: true };
    } else {
      const fullResponse = await response.json();
      return fullResponse;
    }
  } catch (error) {
    console.error('Ollama request failed:', error);
    return { error: "API request failed" };
  }
}
ipcMain.handle('sendMessage', async (event, arg) => {
  var res = await handleOllamaRequest(event, arg);
  return res;
});

ipcMain.handle('getlocales', async () => {
  try {
    console.log(process.cwd())
    const localesPath = path.join('../assets/locales');
    const dirs = await readdir("./assets/locales/", { withFileTypes: true });
    return dirs.filter(d => d.isDirectory()).map(d => d.name);
  } catch (e) {
    console.log(e)
    return ['en',"de","cn","es","fr","ja","ru"];
  }
});

ipcMain.handle('getModels', async () => {
  try {
    const baseModelsPath = path.join(process.cwd(), 'src/assets/models');
    const userModelsPath = path.join(app.getPath('userData'), 'user_models');
    let baseModels: string[] = [];
    let userModels: string[] = [];
    try { baseModels = fs.readdirSync(baseModelsPath).filter(f => f.endsWith('.bpmx') || f.endsWith(".pmx")); } catch { }
    try { userModels = fs.readdirSync(userModelsPath).filter(f => f.endsWith('.bpmx') || f.endsWith(".pmx")); } catch { }
    return { base: baseModels, user: userModels };
  } catch (e) {
    return { base: [], user: [] };
  }
});
ipcMain.handle('get-animations', async () => {
  try {
    const baseAnimsPath = path.join(process.cwd(), 'src/assets/animation');
    const userAnimsPath = path.join(app.getPath('userData'), 'user_animations');
    let baseAnims: string[] = [];
    let userAnims: string[] = [];
    try { baseAnims = fs.readdirSync(baseAnimsPath).filter(f => f.endsWith('.vmd')); } catch { }
    try { userAnims = fs.readdirSync(userAnimsPath).filter(f => f.endsWith('.vmd')); } catch { }
    return { base: baseAnims, user: userAnims };
  } catch (e) {
    return { base: [], user: [] };
  }
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
